const all_post = {
  "posts": [
    {
      "id": 1,
      "username": "marco_builds",
      "handle": "@marco_builds",
      "avatar": "https://i.pravatar.cc/150?img=11",
      "content": "Just deployed my first full-stack app to production. Three months of late nights and it's finally live. Feels unreal.",
      "timestamp": "2024-03-15T14:32:00Z",
      "likes": 284,
      "comments": 47,
      "reposts": 31,
      "bookmarks": 19,
      "tags": ["webdev", "milestone", "javascript"],
      "liked_by_user": false,
      "bookmarked_by_user": false
    },
    {
      "id": 2,
      "username": "priya_thinks",
      "handle": "@priya_thinks",
      "avatar": "https://i.pravatar.cc/150?img=47",
      "content": "Hot take: the best documentation is the kind you write while you still remember why you made the decision. Future you will be grateful.",
      "timestamp": "2024-03-15T11:05:00Z",
      "likes": 1023,
      "comments": 88,
      "reposts": 204,
      "bookmarks": 310,
      "tags": ["programming", "tips"],
      "liked_by_user": true,
      "bookmarked_by_user": true
    },
    {
      "id": 3,
      "username": "dev_lena",
      "handle": "@dev_lena",
      "avatar": "https://i.pravatar.cc/150?img=23",
      "content": "CSS grid changed how I think about layout. Spent two hours reworking a sidebar I had been fighting with for days. Done in 12 lines.",
      "timestamp": "2024-03-14T20:18:00Z",
      "likes": 512,
      "comments": 63,
      "reposts": 97,
      "bookmarks": 140,
      "tags": ["css", "grid", "frontend"],
      "liked_by_user": false,
      "bookmarked_by_user": true
    },
    {
      "id": 4,
      "username": "tech_oluwaseun",
      "handle": "@tech_oluwaseun",
      "avatar": "https://i.pravatar.cc/150?img=68",
      "content": "Reminder that 'it works on my machine' is a valid first step, not a final answer.",
      "timestamp": "2024-03-14T16:45:00Z",
      "likes": 3847,
      "comments": 212,
      "reposts": 891,
      "bookmarks": 504,
      "tags": ["devhumor", "devops"],
      "liked_by_user": true,
      "bookmarked_by_user": false
    },
    {
      "id": 5,
      "username": "junko_designs",
      "handle": "@junko_designs",
      "avatar": "https://i.pravatar.cc/150?img=56",
      "content": "Accessibility is not a feature. It is the baseline. Designing with contrast, focus states, and screen readers in mind from day one saves everyone time.",
      "timestamp": "2024-03-13T09:30:00Z",
      "likes": 760,
      "comments": 54,
      "reposts": 188,
      "bookmarks": 275,
      "tags": ["a11y", "ux", "design"],
      "liked_by_user": false,
      "bookmarked_by_user": false
    },
    {
      "id": 6,
      "username": "rafiq_codes",
      "handle": "@rafiq_codes",
      "avatar": "https://i.pravatar.cc/150?img=33",
      "content": "Started learning TypeScript last week after resisting it for two years. I owe everyone an apology.",
      "timestamp": "2024-03-12T13:10:00Z",
      "likes": 2215,
      "comments": 173,
      "reposts": 445,
      "bookmarks": 198,
      "tags": ["typescript", "javascript", "webdev"],
      "liked_by_user": true,
      "bookmarked_by_user": false
    }
  ]
}
